# vim: expandtab ts=2 sw=2
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.vastdata.com
  labels:
{{- include "vastcsi.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: false
